#!/usr/bin/env bash


apt-get update

passwd -d user

cat > /home/user/.config/powermanagementprofilesrc << EOF
[AC]
icon=battery-charging

[Battery]
icon=battery-060

[LowBattery]
icon=battery-low
EOF
