#!/usr/bin/env bash


apt-get update

passwd -d user

cat > /home/user/.config/powermanagementprofilesrc << EOF
[AC]
icon=battery-charging

[Battery]
icon=battery-060

[LowBattery]
icon=battery-low
EOF

cat > /home/user/.config/kscreenlockerrc << EOF
[Daemon]
Autolock=false
LockOnResume=false
EOF

mkdir -p /home/user/.config/HeliumOS/FirstLogin
cat > /home/user/.config/HeliumOS/FirstLogin/FirstLogin.toml << EOF
install_apps = false
set_launcher_icon = true
EOF

cp -r /etc/skel/* /home/user/
