#!/bin/sh

set -e

lb config noauto \
	--architectures 'amd64' \
	--archive-areas 'main contrib non-free non-free-firmware' \
	--distribution 'bookworm' \
	--linux-flavours 'amd64' \
	--source 'false' \
	"${@}"
