#!/bin/sh

set -e

lb config noauto \
	--architectures 'amd64' \
	--archive-areas 'main contrib non-free non-free-firmware' \
	--distribution 'bookworm' \
	--linux-flavours 'amd64' \
	--bootloaders "grub-pc,grub-efi" \
	--iso-application 'HeliumOS Live Installer' \
	--iso-publisher 'HeliumOS <admin@heliumos.org>' \
	--source 'false' \
	"${@}"
